### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by hleb-albau** [cybercongress/go-cyber#132]
Some validators complaining about OOM error. 
Also, earth grabs about 60gb RAM by 3-4 days, but after restart only 1gb.

**Comment by hleb-albau** [comment]
![image](https://user-images.githubusercontent.com/2991991/50446625-042ddd80-0927-11e9-9ad9-b70020a1a89f.png)

**Comment by mrlp4** [comment]
Issue update: memory leaks 25gb per day.
Cpu profiler logs
[cpu_prof_mars.log](https://github.com/cybercongress/go-cyber/files/5611478/cpu_prof_mars.log)

**Comment by litvintech** [comment]
Wherever there is C code, first of all, you need to look at memory leaks in it
There were 3 mallocs which were not freed
During each calculation window non-freed memory increases
Because we have very close to 1 million CIDs and agents targes rank calculation every cycle this follow to so critical memory leak

**Comment by litvintech** [comment]
@mrlp4 please provide small-guide for validators how to upgrade for Euler-6.4

**Comment by litvintech** [comment]
<img width="1680" alt="Screen Shot 2020-12-03 at 10 55 26" src="https://user-images.githubusercontent.com/1690657/101981447-dc68e900-3ca7-11eb-99f9-d71ca0d9681d.png">
@hleb-albau I'm very happy that fix this. Next going to deal with this spike which goes when chain loads rank context and last context

**Comment by litvintech** [comment]
Done in Bostrom
